CREATE DATABASE IF NOT EXISTS s_hospital;

USE s_hospital;

CREATE TABLE IF NOT EXISTS cuentas(
    id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(120) CHARACTER SET utf8 COLLATE utf8_general_ci UNIQUE,
    password VARCHAR(120) CHARACTER SET utf8 COLLATE utf8_general_ci,
    tipo INT(5) DEFAULT 0,
    token varchar(250) CHARACTER SET utf8 COLLATE utf8_general_ci UNIQUE,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS persona(
    id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(120) CHARACTER SET utf8 COLLATE utf8_general_ci,
    apellidos VARCHAR(120) CHARACTER SET utf8 COLLATE utf8_general_ci,
    carnet VARCHAR(120) CHARACTER SET utf8 COLLATE utf8_general_ci UNIQUE,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS paciente(
    id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fechaNacimiento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sexo INT(2)

);

CREATE TABLE IF NOT EXISTS pacienteMedico(
    idPaciente INT(20) NOT NULL,
    idMedico INT(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS temperatura(
    id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    temperatura FLOAT(10) NOT NULL,
    idPaciente INT(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS saturacionO2(
    id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    saO2 FLOAT(10) NOT NULL,
    idPaciente INT(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS pulsoCardiaco(
    id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pulsoCard FLOAT(10) NOT NULL,
    idPaciente INT(20) NOT NULL
);


CREATE TABLE IF NOT EXISTS dispositivo(
    id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    token FLOAT(10) NOT NULL,
    idMedico INT(20) NOT NULL
);